### ISSUE TITLE
Single distribution file

### ISSUE THREAD

**Issue by taf2** [team-telnyx/webrtc-examples#36]
It would be very nice if we could download a single file to get access to the telnyx.js file.  We handle distribution of js assets without npm etc... especially today since ES6 is available natively in all browsers...  This would make it much easier for developers to get started too..

**Comment by RJSkorski** [comment]
Hi @taf2 
thanks for your suggestions. There are 2 external CDNs that can be used for installing the SDK:

- https://unpkg.com/@telnyx/webrtc
- https://cdn.jsdelivr.net/npm/@telnyx/webrtc

The documentation was updated with them too: https://developers.telnyx.com/docs/v2/voice/webrtc/resources/js_client/
